"use strict";(()=>{var e={};e.id=703,e.ids=[703],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},62754:(e,t,o)=>{o.r(t),o.d(t,{originalPathname:()=>g,patchFetch:()=>h,requestAsyncStorage:()=>p,routeModule:()=>d,serverHooks:()=>m,staticGenerationAsyncStorage:()=>f});var r={};o.r(r),o.d(r,{GET:()=>c});var n=o(49303),a=o(88716),i=o(60670),s=o(55661),l=o(24130),u=o(60707);async function c(){let e=await {rules:{userAgent:"*",allow:"/"},sitemap:`${l.J.url}/sitemap.xml`},t=(0,u.resolveRouteData)(e,"robots");return new s.NextResponse(t,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let d=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2Fmnt%2Fd%2FCoderZone%2FComapny%20website%2Ffrontend%2Fsrc%2Fapp%2Frobots.js&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:r}),{requestAsyncStorage:p,staticGenerationAsyncStorage:f,serverHooks:m}=d,g="/robots.txt/route";function h(){return(0,i.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:f})}},60707:(e,t,o)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var o in t)Object.defineProperty(e,o,{enumerable:!0,get:t[o]})}(t,{resolveManifest:function(){return i},resolveRobots:function(){return n},resolveRouteData:function(){return s},resolveSitemap:function(){return a}});let r=o(91389);function n(e){let t="";for(let o of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,r.resolveArray)(o.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(o.allow)for(let e of(0,r.resolveArray)(o.allow))t+=`Allow: ${e}
`;if(o.disallow)for(let e of(0,r.resolveArray)(o.disallow))t+=`Disallow: ${e}
`;o.crawlDelay&&(t+=`Crawl-delay: ${o.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,r.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function a(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),o="";for(let n of(o+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?o+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':o+=">\n",e)){var r;o+=`<url>
<loc>${n.url}</loc>
`;let e=null==(r=n.alternates)?void 0:r.languages;if(e&&Object.keys(e).length)for(let t in e)o+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(n.lastModified){let e=n.lastModified instanceof Date?n.lastModified.toISOString():n.lastModified;o+=`<lastmod>${e}</lastmod>
`}n.changeFrequency&&(o+=`<changefreq>${n.changeFrequency}</changefreq>
`),"number"==typeof n.priority&&(o+=`<priority>${n.priority}</priority>
`),o+="</url>\n"}return o+"</urlset>\n"}function i(e){return JSON.stringify(e)}function s(e,t){return"robots"===t?n(e):"sitemap"===t?a(e):"manifest"===t?i(e):""}},91389:(e,t)=>{function o(e){return Array.isArray(e)?e:[e]}function r(e){if(null!=e)return o(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var o in t)Object.defineProperty(e,o,{enumerable:!0,get:t[o]})}(t,{resolveArray:function(){return o},resolveAsArrayOrUndefined:function(){return r}})},24130:(e,t,o)=>{o.d(t,{J:()=>r});let r={name:"Coderzon",legalName:"Coderzon Technologies Pvt Ltd",url:"https://www.coderzon.com",logo:"/images/logo.webp",yearsExperience:20,description:"At CODERZON, we provide top-tier technology consulting and recruitment services, helping businesses thrive with tailored digital solutions and access to the industry's best tech talent.",contact:{email:"contact@coderzon.com",phone:"(+91) 8301890158",phoneHref:"tel:+918301890158",address:"CODERZON Technologies Pvt Ltd, AKL Heights, Seaport Road, Near Bharathmatha College, Kochi, Kerala - 682021",mapsUrl:"https://maps.google.com/?q=Coderzon+Technologies+Kochi",officeHours:["Monday - Friday","9:00 AM to 6:00 PM"]},keywords:["Coderzon Technologies Pvt Ltd","AI software development","data analytics consulting","business intelligence solutions","cloud computing services","web application development","custom software development","software company in India","enterprise software solutions","mobile app development","legacy software modernization","digital transformation company","machine learning development","SaaS product development","technology consulting firm"]}}};var t=require("../../webpack-runtime.js");t.C(e);var o=e=>t(t.s=e),r=t.X(0,[948,518],()=>o(62754));module.exports=r})();